//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by xswstatistic.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_XSWSTATISTIC_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDC_KILLER1                     1000
#define IDC_KILLER2                     1001
#define IDC_KILLER3                     1002
#define IDC_KILLER4                     1003
#define IDC_KILLED1                     1004
#define IDC_KILLED2                     1005
#define IDC_KILLED3                     1006
#define IDC_KILLED4                     1007
#define IDC_KILL11                      1008
#define IDC_KILL12                      1009
#define IDC_KILL13                      1010
#define IDC_KILL14                      1011
#define IDC_KILL21                      1012
#define IDC_KILL22                      1013
#define IDC_KILL23                      1014
#define IDC_KILL24                      1015
#define IDC_KILL31                      1016
#define IDC_KILL32                      1017
#define IDC_KILL33                      1018
#define IDC_KILL34                      1019
#define IDC_KILL41                      1020
#define IDC_KILL42                      1021
#define IDC_KILL43                      1022
#define IDC_KILL44                      1023
#define IDC_ACCFIRE1                    1024
#define IDC_ACCFIRE2                    1025
#define IDC_ACCFIRE3                    1026
#define IDC_ACCFIRE4                    1027
#define IDC_TOTALKILLS1                 1028
#define IDC_TOTALKILLS2                 1029
#define IDC_TOTALKILLS3                 1030
#define IDC_TOTALKILLS4                 1031
#define IDC_SHOTS1                      1032
#define IDC_SHOTS2                      1033
#define IDC_SHOTS3                      1034
#define IDC_SHOTS4                      1035
#define IDC_FIRE1                       1036
#define IDC_FIRE2                       1037
#define IDC_FIRE3                       1038
#define IDC_FIRE4                       1039
#define IDC_HITS1                       1040
#define IDC_HITS2                       1041
#define IDC_HITS3                       1042
#define IDC_HITS4                       1043
#define IDC_DEATHS1                     1044
#define IDC_FRAGS1                      1045
#define IDC_DEATHS2                     1046
#define IDC_DEATHS3                     1047
#define IDC_DEATHS4                     1048
#define IDC_FRAGS2                      1049
#define IDC_FRAGS3                      1050
#define IDC_FRAGS4                      1051
#define IDC_SUICIDES1                   1052
#define IDC_SUICIDES2                   1053
#define IDC_SUICIDES3                   1054
#define IDC_SUICIDES4                   1055
#define IDC_TOTALKILLED1                1056
#define IDC_TOTALKILLED2                1057
#define IDC_TOTALKILLED3                1058
#define IDC_TOTALKILLED4                1059

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
