//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by start_new.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_START_NEW_DIALOG            102
#define IDS_OPTIONS                     102
#define IDR_MAINFRAME                   128
#define IDD_PLAYERS                     129
#define IDD_OPTIONS1                    132
#define IDD_OPTIONS2                    133
#define IDD_OPTIONS3                    135
#define IDD_SHIPSELECT                  139
#define IDD_OPTIONS4                    140
#define IDD_ASTEROIDS                   145
#define IDD_SOUND                       146
#define IDC_STARTMULTI                  1000
#define IDC_OPTIONS                     1001
#define IDC_CREDITS                     1002
#define IDC_EXIT                        1003
#define IDC_STATS                       1004
#define IDC_PLAYERS                     1005
#define IDC_CONTROL2                    1008
#define IDC_CONTROL3                    1009
#define IDC_CONTROL4                    1010
#define IDC_CONTROL1                    1011
#define IDC_BORG                        1015
#define IDC_BORGTIME                    1016
#define IDC_COLORDEPTH                  1021
#define IDC_SOUND                       1021
#define IDC_GAMESPEED                   1022
#define IDC_TRIPLEBUFFERING             1023
#define IDC_WINDOWMODE                  1024
#define IDC_RESX                        1025
#define IDC_IMAGE                       1026
#define IDC_RESY                        1026
#define IDC_INFO                        1027
#define IDC_NAME1                       1028
#define IDC_NAME2                       1029
#define IDC_NAME3                       1030
#define IDC_LOADPICTURE                 1030
#define IDC_NAME4                       1031
#define IDC_DEATHSOUND                  1031
#define IDC_EDITOR                      1032
#define IDC_CDTRACK                     1032
#define IDC_ANIMATE1                    1034
#define IDC_SHIPS                       1035
#define IDC_UP1                         1039
#define IDC_RIGHT1                      1040
#define IDC_CHECK1                      1040
#define IDC_DOWN1                       1041
#define IDC_CHECK2                      1041
#define IDC_CDPLAY                      1041
#define IDC_LEFT1                       1042
#define IDC_CHECK3                      1042
#define IDC_FIRE1                       1043
#define IDC_CHECK4                      1043
#define IDC_KEYBOARD                    1044
#define IDC_CHECK5                      1044
#define IDC_CHECK6                      1045
#define IDC_SPECIAL                     1045
#define IDC_CHECK7                      1046
#define IDC_CHECK8                      1047
#define IDC_CHECK9                      1048
#define IDC_INTERVAL                    1052
#define IDC_DISTANCE                    1053
#define IDC_COUNT                       1054
#define IDC_SPEED                       1055
#define IDC_RADIUS                      1056
#define IDC_ASTEROIDS                   1057
#define IDC_SFX                         1058
#define IDC_MUSIC                       1059
#define IDC_SPEECH                      1060
#define IDC_MASTER                      1061

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
