//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDR_WAVEMENU                    102
#define IDD_ABOUT                       103
#define ID_INFO_ABOUT                   40001
#define ID_DATEI_BEENDEN                40002
#define ID_ANSICHT_HINTERGRUNDFARBE     40003
#define ID_WELLE_AUSLOESEN              40004
#define ID_EINSTELLUNGEN_ENGINEINFO_EIN 40007
#define ID_EINSTELLUNGEN_ENGINEINFO_AUS 40008
#define ID_ANSICHT_WELLENFARBE          40009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40010
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
