//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by iniedit.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_INIEDIT_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDC_TREE1                       1000
#define IDC_SAVE                        1005
#define IDC_NEW                         1006
#define IDC_DELETE                      1007
#define IDC_EDIT                        1008
#define IDC_RELOAD                      1009
#define IDC_EXIT                        1010
#define IDC_SORT                        1011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
