//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by keyboard.rc
//
#define IDD_KEYBOARD_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDC_A                           1004
#define IDC_B                           1005
#define IDC_C                           1006
#define IDC_D                           1007
#define IDC_E                           1008
#define IDC_F                           1009
#define IDC_G                           1010
#define IDC_H                           1011
#define IDC_I                           1012
#define IDC_J                           1013
#define IDC_K                           1014
#define IDC_L                           1015
#define IDC_M                           1016
#define IDC_N                           1017
#define IDC_O                           1018
#define IDC_P                           1019
#define IDC_Q                           1020
#define IDC_R                           1021
#define IDC_W                           1022
#define IDC_T                           1023
#define IDC_U                           1024
#define IDC_V                           1025
#define IDC_S                           1026
#define IDC_X                           1027
#define IDC_Y                           1028
#define IDC_Z                           1029
#define IDC_EDIT1                       1030
#define IDC_EDIT2                       1031
#define IDC_EDIT3                       1032
#define IDC_EDIT4                       1033
#define IDC_EDIT5                       1034
#define IDC_EDIT6                       1035
#define IDC_EDIT7                       1036
#define IDC_EDIT8                       1037
#define IDC_EDIT9                       1038
#define IDC_EDIT10                      1039
#define IDC_EDIT11                      1040
#define IDC_EDIT12                      1041
#define IDC_EDIT13                      1042
#define IDC_EDIT14                      1043
#define IDC_EDIT15                      1044
#define IDC_EDIT16                      1045
#define IDC_EDIT17                      1046
#define IDC_EDIT18                      1047
#define IDC_EDIT19                      1048
#define IDC_EDIT20                      1049
#define IDC_EDIT21                      1050
#define IDC_EDIT22                      1051
#define IDC_EDIT23                      1052
#define IDC_EDIT24                      1053
#define IDC_EDIT25                      1054
#define IDC_EDIT26                      1055
#define IDC_CHECK1                      1056

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
