//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by fa.rc
//
#define IDD_FA_DIALOG                   102
#define IDR_MAINFRAME                   128
#define IDC_OPENNAME                    1000
#define IDC_OPEN                        1001
#define IDC_CLOSE                       1002
#define IDC_LIST                        1003
#define IDC_ADD                         1004
#define IDC_ADDNAME                     1005
#define IDC_EXTRACT                     1006
#define IDC_KEY                         1007
#define IDC_ADDDIR                      1008
#define IDC_DELETE                      1009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
