//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DPTest.rc
//
#define IDD_DPTEST_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_SESSIONS                    129
#define IDD_PLAYERS                     130
#define IDC_LIST1                       1000
#define IDC_SELECT                      1001
#define IDC_CREATE                      1002
#define IDC_JOIN                        1003
#define IDC_UPDATE                      1004
#define IDC_CHAT                        1005
#define IDC_SEND                        1006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
